### PR TITLE
Avoid "use strict"; string

### LINKED ISSUE #10: 'use strict' statement not removed
In firefox, when strict mode is on, `Function#toString()` returns string with an extra `'use strict'` statement.

```js
;(function() {
  'use strict'
  return heredoc(function() {/*
    hello world
  */})
}()

// ""use strict";
// /*
//     hello world
// "
```

### PR DESCRIPTION
**Pull request by dotnil**
In firefox, when strict mode is on, Function#toString will return
string that contain `"use strict";` statement anyway. Hence we shall use
regular expression to extract the comment content specifically.

This commit fixes #10; multiline haven't got that issue, but I cannot afford switching. I've been using heredoc over lots of places in my projects. So I setup browser testing and shamelessly copied and modified the regular expression used in multiline. Here's this PR.

### CODE REVIEW

**Comment by jden** [comment]
When I run the tests I get 

```
 9:43> npm test

> heredoc@1.3.0 test ~/dev/jden/heredoc
> node node_modules/mocha/bin/mocha


~/dev/jden/heredoc/test/runner.js:7
mocha.run()
^
ReferenceError: mocha is not defined
```

**Comment by dotnil** [comment]
@jden Sorry about that. It's fixed now.

**Comment by dotnil** [comment]
It seems mocha will just use runner.js if there's one. I wasn't aware of that.

**Comment by jden** [comment]
Great, thanks!

**Comment by jden** [comment]
landed in [heredoc@1.3.1](https://www.npmjs.com/package/heredoc)

**Comment by dotnil** [comment]
Awesome!

**Pull request merged**
